name: Build Examples
on: [push]
jobs:
  build-examples:
    strategy:
      matrix:
        go-version: ['1.20', '1.19']
        tinygo-version: ['0.27.0', '0.26.0']
        exclude:
          - go-version: '1.20'
            tinygo-version: '0.26.0'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fastly/compute-sdk-go
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
         go-version: ${{ matrix.go-version }}
      - name: Install TinyGo
        uses: ./.github/actions/install-tinygo
        with:
          tinygo-version: ${{ matrix.tinygo-version }}
      - name: Build examples
        run: |
          for i in _examples/*; do
            echo ${GITHUB_WORKSPACE}/$i
            cd ${GITHUB_WORKSPACE}/$i && tinygo build -target=wasi
          done
      - name: Build integration tests
        run: |
          for i in _integration_tests/fixtures/*; do
            echo ${GITHUB_WORKSPACE}/$i
            cd ${GITHUB_WORKSPACE}/$i && tinygo build -target=wasi
          done
