name: Compute TinyGo SDK Test
on: [push]
jobs:
  sdktest:
    runs-on: ubuntu-latest
    concurrency: 
      group: SdkTestJob
      cancel-in-progress: true
    steps:
      - name: Checkout fastly/compute-sdk-go
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - name: Install TinyGo
        uses: ./.github/actions/install-tinygo
        with:
          tinygo-version: '0.27.0'
      - uses: ./.github/actions/bootstrap-integration-test
      - name: Check our bootstrap dependencies were installed correctly, and in our $PATH
        run: |
          go version
          tinygo version
          fastly version
          viceroy --version
      - name: compute-sdk-go Integration Tests Job
        uses: ./.github/actions/compute-sdk-test
        id: sdktest
        with:
          config: './_integration_tests/sdk-test-config.json'
