name: Integration Tests
on: [push]
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fastly/compute-sdk-go
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.20.0'
      - name: Install TinyGo
        uses: ./.github/actions/install-tinygo
        with:
          tinygo-version: '0.28.1'
      - uses: ./.github/actions/bootstrap-integration-test
      - name: Check our bootstrap dependencies were installed correctly, and in our $PATH
        run: |
          go version
          tinygo version
          fastly version
          viceroy --version
      - name: Run Integration Tests
        run: tinygo test -v -target=compute-at-edge.json ./integration_tests/...
